executable = /bin/bash
arguments = src/baselines/run_baseline.sh $(eval) $(model) $(Cluster)
environment = "OPENAI_API_KEY=$ENV(OPENAI_API_KEY) ANTHROPIC_API_KEY=$ENV(ANTHROPIC_API_KEY) GEMINI_API_KEY=$ENV(GEMINI_API_KEY) HOME=$ENV(HOME)"
error = test_$(Cluster).err
output = test_$(Cluster).out
log = test_$(Cluster).log
request_memory = 32768
request_cpus = 16
request_gpus = 1
requirements = TARGET.CUDADeviceName == "NVIDIA H100 80GB HBM3"
request_disk=200G
+BypassLXCfs="true"
queue