#!/usr/bin/env python3
"""Generate Harbor tasks for the PostTrainBench sweep.

One task per (benchmark, model) cell — 28 in the full sweep, the same matrix
`src/commit_utils/commit.sh` submits to HTCondor.

Design rule, applied everywhere: **do not reimplement anything the repo
already does.** The agent prompt comes from `src/eval/general/get_prompt.py`,
run as a subprocess with the same arguments `run_task.sh:75` passes. The
judge prompts come from `src/judges/get_judge_prompt.py`, invoked by the
verifier at run time. `timer.sh` comes from `src/utils/create_timer.sh`,
invoked in the container at start time. Every file the sandbox needs is
copied out of the checkout rather than transcribed. The only new code is the
Harbor plumbing that has no upstream counterpart: task.toml, the two
Dockerfiles, preflight.sh, test.sh and score_run.py.

The staging layout mirrors upstream paths exactly, so relative paths inside
copied scripts keep resolving:

    environment/home/  ->  the JOB_DIR run_task.sh:55-155 assembles
    tests/repo/        ->  the subtree the judge and evaluation phases read

Usage:

    python src/kaggle_harbor/build_tasks.py --all --agent codex --output ./tasks
    python src/kaggle_harbor/build_tasks.py --benchmark gsm8k \\
        --model Qwen/Qwen3-1.7B-Base --agent claude --output ./tasks
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import config as cfg  # noqa: E402

TEMPLATE_DIR = Path(__file__).resolve().parent / "template"
REPO_ROOT = cfg.REPO_ROOT

# The `--agent` value handed to get_prompt.py, always, whatever the row's real
# agent is.
#
# get_prompt.py uses args.agent in exactly one place — the `if 'claude' in
# args.agent` at :120 — so the name changes the output only by adding or not
# adding the non-interactive clause. A Harbor task has one instruction.md
# shared by every harness, so the baked prompt must be the clause-free one and
# agents/ptb_harness.py re-applies the clause per harness at run time.
#
# It cannot simply be the row's own name: a claude row's true name is
# `claude`, which would bake the clause in, but that same true name is what
# metadata.json has to carry for parse_trace.py:36-44 and
# get_judge_prompt.py:83 (build_agent_harness_clause). Separating the two
# lets both be right. Any string without 'claude' produces byte-identical
# output; verify_fidelity.py asserts that per task by regenerating with the
# row's real name.
PROMPT_AGENT = "ptb"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.is_dir():
        shutil.copytree(src, dst, dirs_exist_ok=True)
    else:
        shutil.copy2(src, dst)


def _compose_override(dest: Path, torch_backend: str, binds: list[str],
                      extra_args: dict[str, str] | None = None) -> None:
    """Write a `docker-compose.yaml` beside a Dockerfile, for what task.toml can't say.

    Harbor layers `<environment_dir>/docker-compose.yaml` over its own generated
    stack when the file exists (`environments/docker/docker.py:363-364`,
    `_environment_docker_compose_path`), and it does so for the agent
    environment and the separate verifier environment alike. That makes this
    the only seam for two things task.toml cannot express:

    * **build args.** Harbor's build file is
      `build: {context: ${CONTEXT_DIR}}` with no `args:`
      (`environments/docker/docker-compose-build.yaml`), and nothing in the
      Kaggle path passes `--build-arg`. Both Dockerfiles declare
      `ARG TORCH_BACKEND=auto` and use it on the `uv pip install vllm` line,
      so without this the ARG default is the only reachable value.
    * **bind mounts into the verifier**, which `--mounts` never reaches
      (see stage_tests).

    The service name must be `main` — that is what harbor's own files declare.
    """
    lines = ["# Generated by build_tasks.py. Harbor layers this over its own",
             "# compose stack; see _compose_override() for why it must exist.",
             "services:",
             "  main:"]
    args = dict(extra_args or {})
    if torch_backend:
        args["TORCH_BACKEND"] = torch_backend
    if args:
        # Only meaningful when harbor actually builds. With a prebuilt
        # docker_image there is no build step, so emitting build.args would be
        # misleading noise — but the volumes below are still required, because
        # this file remains the only way a mount reaches the verifier.
        #
        # PTB_VERIFIER_BASE rides the same channel and for the same reason:
        # harbor's build file declares no `args:`, so a build ARG has no other
        # route into the image.
        lines += ["    build:", "      args:"]
        lines += [f"        {k}: {v}" for k, v in sorted(args.items())]
    if binds:
        lines.append("    volumes:")
        lines.extend(f"      - {b}" for b in binds)
    if len(lines) <= 4:
        # Nothing to say: no build args (prebuilt image) and no binds. A
        # `services: main:` with an empty body is not valid compose, and
        # harbor layers this file blindly if it exists, so write nothing.
        dest.unlink(missing_ok=True)
        return
    dest.write_text("\n".join(lines) + "\n")


def _require(path: Path, why: str) -> Path:
    if not path.exists():
        raise FileNotFoundError(f"{path} not found — {why}")
    return path


def read_benchmark_name(benchmark_id: str) -> str:
    """get_prompt.py:17 — the human-readable name, from benchmark.txt."""
    return (
        REPO_ROOT / "src" / "eval" / "tasks" / benchmark_id / "benchmark.txt"
    ).read_text(encoding="utf-8").strip()


def read_required_api_keys(benchmark_id: str) -> list[str]:
    """get_prompt.py:24 — provider keys this benchmark's own grading needs.

    run_task.sh:96-121 provisions the agent sandbox with exactly
    `agents/<agent>/api_keys.json` ∪ this list. The agent half of that
    allowlist has no analogue here (harbor injects model credentials
    unconditionally), but the benchmark half is reproduced: only the
    benchmarks that declare a key get it in [environment.env].
    """
    info = json.loads(
        (REPO_ROOT / "src" / "eval" / "tasks" / benchmark_id / "info.json")
        .read_text(encoding="utf-8")
    )
    return info.get("required_api_keys", [])


def generate_instruction(
    benchmark_id: str, model_to_train: str, num_hours: str, agent: str, num_gpus: int
) -> str:
    """Run get_prompt.py exactly as run_task.sh:75 does.

    A subprocess rather than an import: get_prompt.py resolves
    `src/eval/tasks/...` relative to the working directory, so it has to run
    from the repo root, and shelling out guarantees the output is whatever
    upstream would have produced — including the trailing claude clause and
    the `{setup_other}` / `{decontamination_tool}` / `{eval_api_note}`
    branches.
    """
    result = subprocess.run(
        [
            sys.executable,
            "src/eval/general/get_prompt.py",
            "--model-to-train", model_to_train,
            "--benchmark-id", benchmark_id,
            "--num-hours", num_hours,
            "--num-gpus", str(num_gpus),
            "--agent", agent,
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"get_prompt.py failed for {benchmark_id}/{model_to_train}:\n"
            f"{result.stderr}"
        )
    # run_task.sh:76 captures stdout through `$( )`, which strips trailing
    # newlines, then writes it back with `echo`. Net effect: exactly one
    # trailing newline.
    return result.stdout.rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# environment/ — the agent container build context
# ---------------------------------------------------------------------------

def _compose_dotenv(project_dir: Path) -> None:
    """Ship an empty `.env` wherever docker compose will look for one.

    D232. `docker compose` stats `.env` in its --project-directory on EVERY
    invocation, and harbor points that at the task's directory on the gcsfuse
    mount (environments/docker/docker.py:620). Nothing of ours references the
    file; compose looks for it unconditionally.

    With no file present that is a NEGATIVE lookup, and the Kaggle mount runs
    gcsfuse with --implicit-dirs. gcsfuse cannot answer ENOENT straight from
    the 404: it must issue an `objects.list` with prefix `.env/` to rule out an
    implicit directory. If that list call hits a blip -- 503, timeout -- the
    layer returns **EIO instead of ENOENT**. Compose ignores ENOENT and treats
    EIO as fatal, exits 1, and the command dies under `set -euo pipefail`
    before it has run. That is how a claude-code install died on a path it
    never mentions (run 1120769; verified against GCS artifacts and gcsfuse
    mount.go:147 by the Benchmarks team).

    A 0-byte file turns the negative lookup into a positive one: GCS answers
    200, gcsfuse caches the metadata locally, and no objects.list is ever
    issued for it again. Compose parses an empty .env to zero variables, so
    there is no behavioural change.

    Not a fix for the underlying fault -- fleet-wide this costs 0.15-5.84% of
    all Harbor runs -- but it removes the condition that triggers it for ours.
    """
    (project_dir / ".env").write_text("")


def stage_environment(
    task_dir: Path, benchmark_id: str, eval_script: str,
    allow_missing_test_data: bool, torch_backend: str,
    docker_image: str | None, smoke: bool,
    agent_base_image: str | None = None,
) -> None:
    env_dir = task_dir / "environment"
    env_dir.mkdir(parents=True, exist_ok=True)
    _compose_dotenv(env_dir)          # D232

    # A smoke build swaps in a lightweight base with the same layout; see
    # template/environment/Dockerfile.smoke for what it does and does not
    # cover.
    # agent_base_image => build a thin per-task layer on that base, so this
    # task's own home/ actually reaches /home/ben. A prebuilt `docker_image`
    # makes harbor pull and never build, which is how every agent ended up
    # with gsm8k's evaluate.py -- see the comment at the top of
    # environment/Dockerfile.perTask.
    if agent_base_image and not smoke:
        src_dockerfile = "Dockerfile.perTask"
    else:
        src_dockerfile = "Dockerfile.smoke" if smoke else "Dockerfile"
    _copy(TEMPLATE_DIR / "environment" / src_dockerfile, env_dir / "Dockerfile")
    _copy(TEMPLATE_DIR / "environment" / "preflight.sh", env_dir / "preflight.sh")
    # Delivers ARG TORCH_BACKEND, which nothing else on the Kaggle path can,
    # and PTB_AGENT_BASE for the per-task build.
    _compose_override(env_dir / "docker-compose.yaml",
                      "" if (docker_image and not agent_base_image) else torch_backend, [],
                      {"PTB_AGENT_BASE": agent_base_image}
                      if agent_base_image and not smoke else None)
    _copy(
        REPO_ROOT / "containers" / "requirements-direct.txt",
        env_dir / "requirements-direct.txt",
    )

    home = env_dir / "home"
    task = home / "task"
    task.mkdir(parents=True, exist_ok=True)

    tasks_dir = REPO_ROOT / "src" / "eval" / "tasks" / benchmark_id

    # run_task.sh:63 — the chosen eval script always lands as evaluate.py.
    _copy(_require(tasks_dir / eval_script, "the agent's eval entry point"),
          task / "evaluate.py")

    # run_task.sh:64-66
    if (tasks_dir / "evaluation_code").is_dir():
        _copy(tasks_dir / "evaluation_code", task / "evaluation_code")

    # run_task.sh:67
    _copy(REPO_ROOT / "src" / "eval" / "templates", task / "templates")

    # run_task.sh:69-71 — task_context contents are flattened into task/.
    task_context = tasks_dir / "task_context"
    if task_context.is_dir():
        for item in task_context.iterdir():
            _copy(item, task / item.name)

    # run_task.sh:72
    _copy(REPO_ROOT / "containers" / "other_home_data" / ".codex", home / ".codex")

    # run_task.sh:124-128 — the scripts the agent phase runs in the sandbox.
    # create_timer.sh is added to this set: upstream runs it on the host
    # during job prep, and preflight.sh runs it in-container instead (see
    # its header).
    for name in (
        "check_cuda.py",
        "check_cuda_writing.py",
        "system_monitor.sh",
        "timestamp_lines.py",
        "update_agent_cli.sh",
        "create_timer.sh",
    ):
        _copy(REPO_ROOT / "src" / "utils" / name, home / name)

    # run_task.sh:136-141 — the agent's self-decontamination tooling.
    # Upstream hard-errors when test_data.json is absent, because its
    # presence also decides whether get_prompt.py emits the "Decontamination
    # Tool" section. A build without it produces a different prompt, so the
    # override has to be explicit.
    test_data = tasks_dir / "test_data.json"
    if not test_data.exists():
        if not allow_missing_test_data:
            raise FileNotFoundError(
                f"src/eval/tasks/{benchmark_id}/test_data.json not found — "
                f"required for the agent's decontamination tooling "
                f"(run_task.sh:136). Fetch it with "
                f"src/judges/test_data_download/download_test_data.sh, or pass "
                f"--allow-missing-test-data to build a task whose prompt omits "
                f"the Decontamination Tool section."
            )
        print(
            f"  WARNING: no test_data.json for {benchmark_id}; the generated "
            f"prompt omits the Decontamination Tool section and the "
            f"contamination judge has no reference set."
        )
    else:
        _copy(test_data, home / "test_data.json")
    _copy(
        REPO_ROOT / "src" / "judges" / "judge_tools" / "contamination_check.py",
        home / "contamination_check.py",
    )


# ---------------------------------------------------------------------------
# tests/ — the verifier container build context
# ---------------------------------------------------------------------------

def stage_tests(
    task_dir: Path,
    benchmark_id: str,
    model_to_train: str,
    agent: str,
    agent_config: str,
    judge_model_map: dict[str, str],
    metadata: dict,
    hf_cache_mounts: list[str],
    torch_backend: str,
    verifier_docker_image: str | None,
    verifier_base_image: str | None,
    smoke: bool,
) -> None:
    tests_dir = task_dir / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    _compose_dotenv(tests_dir)        # D232

    # A base image means harbor BUILDS this task's verifier from the thin
    # Dockerfile, layering the task's own tests/ over prebuilt heavy layers.
    # That is the only way per-task /tests reaches a separate verifier env --
    # see the comment at the top of Dockerfile.perTask.
    if verifier_base_image and not smoke:
        src_name = "Dockerfile.perTask"
    else:
        src_name = "Dockerfile.smoke" if smoke else "Dockerfile"
    _copy(TEMPLATE_DIR / "tests" / src_name, tests_dir / "Dockerfile")
    # strip_web_search.py is the PTB_DISABLE_WEB_SEARCH=1 diagnostic shim; it
    # is inert unless that env var is set (see test.sh). Staged unconditionally
    # so a diagnostic run needs an env var, not a rebuild.
    for name in ("test.sh", "score_run.py", "strip_web_search.py"):
        _copy(TEMPLATE_DIR / "tests" / name, tests_dir / name)
    _copy(
        REPO_ROOT / "containers" / "requirements-direct.txt",
        tests_dir / "requirements-direct.txt",
    )

    # A partial checkout at the upstream paths. judge_lib.sh, test.sh and
    # get_judge_prompt.py all navigate relative to a repo root, and
    # evaluate.py is invoked with `--templates-dir ../../../../src/eval/
    # templates`; keeping the layout means none of them need patching.
    repo = tests_dir / "repo"

    _copy(
        REPO_ROOT / "src" / "eval" / "tasks" / benchmark_id,
        repo / "src" / "eval" / "tasks" / benchmark_id,
    )
    _copy(REPO_ROOT / "src" / "eval" / "templates", repo / "src" / "eval" / "templates")

    # run_task.sh:324 runs src/trace_parsing/parse_trace.py from the repo root.
    # The parsers import each other as flat siblings (parse_trace.py:20-25,
    # claude_parser.py:10), which works because python puts a script's own
    # directory on sys.path — so the whole package has to land at the upstream
    # path and be invoked the upstream way. __pycache__ is a build artefact of
    # the checkout, not part of the source.
    _copy(REPO_ROOT / "src" / "trace_parsing", repo / "src" / "trace_parsing")
    shutil.rmtree(repo / "src" / "trace_parsing" / "__pycache__", ignore_errors=True)

    # parse_trace.py:81 calls sanitize_trace.load_api_key_secrets(), which
    # hard-exits when there is no .env at sanitize_trace.py's
    # parents[2] (sanitize_trace.py:14-15, :33-34) — i.e. at the repo root.
    # Upstream's repo root always has one. example.env is that file's shipped
    # template and carries the `*_API_KEY` names; load_api_key_secrets prefers
    # the live environment value over the file's `your-*` placeholder
    # (sanitize_trace.py:47), so staging the template reproduces upstream's
    # redaction exactly without baking a secret into the image.
    _copy(REPO_ROOT / "example.env", repo / ".env")

    judges_src = REPO_ROOT / "src" / "judges"
    judges_dst = repo / "src" / "judges"
    _copy(judges_src / "get_judge_prompt.py", judges_dst / "get_judge_prompt.py")
    _copy(judges_src / "judge_tools", judges_dst / "judge_tools")
    for judge in cfg.ALL_JUDGES:
        _copy(judges_src / judge / "judge.conf", judges_dst / judge / "judge.conf")
        _copy(judges_src / judge / "prompt.md", judges_dst / judge / "prompt.md")

    _copy(
        REPO_ROOT / "containers" / "delete_hf_models.py",
        repo / "containers" / "delete_hf_models.py",
    )
    _copy(
        REPO_ROOT / "containers" / "other_home_data" / ".codex",
        repo / "containers" / "other_home_data" / ".codex",
    )

    # This compose file is the ONLY way to get the HF cache into the SEPARATE
    # verifier container.
    #
    # Harbor appends `--mounts` (how a Kaggle dataset mount arrives) to the
    # agent environment only — trial/trial.py:1299 is `base +
    # list(self.config.environment.mounts or [])`, while the verifier env is
    # built from trial/trial.py:681-692, a single fixed bind of /logs/verifier.
    # task.toml cannot help: EnvironmentConfig has no `mounts` field
    # (models/task/config.py:421) and, because pydantic `extra` is left at
    # "ignore", writing one is silently dropped rather than rejected.
    # `extra_docker_compose` is blanked for the verifier at trial/trial.py:648.
    # Upstream needs no equivalent — it binds the same overlay into the
    # evaluation phase directly (run_task.sh:410-411).
    #
    # The path is written literally rather than interpolated: `${VAR}` would
    # resolve against the verifier's env, where PTB_HF_CACHE_MOUNT need not be
    # set, and an empty expansion produces a malformed bind. If the source
    # does not exist docker creates an empty directory, so a run without the
    # cache dataset degrades to the previous behaviour instead of failing.
    _compose_override(
        tests_dir / "docker-compose.yaml",
        "" if verifier_docker_image else torch_backend,
        [f"{m}:{m}:ro" for m in hf_cache_mounts],
        {"PTB_VERIFIER_BASE": verifier_base_image} if verifier_base_image and not smoke else None,
    )

    (tests_dir / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
    (tests_dir / "judge_model_map.json").write_text(
        json.dumps(judge_model_map, indent=2) + "\n"
    )


# ---------------------------------------------------------------------------
# task.toml
# ---------------------------------------------------------------------------

def render_task_toml(
    *,
    slug: str,
    benchmark_id: str,
    benchmark_name: str,
    model_to_train: str,
    num_hours: int,
    agent_timeout_sec: float,
    verifier_timeout_sec: float,
    hf_cache_mounts: list[str],
    skip_cuda_check: bool,
    docker_image: str | None,
    agent_base_image: str | None,
    verifier_docker_image: str | None,
    gpu_types: list[str],
    cpus: int,
    memory_mb: int,
    storage_mb: int,
    smoke: bool,
) -> str:
    required_keys = read_required_api_keys(benchmark_id)

    def resources(indent_header: str, image: str | None = None) -> str:
        # environments/definition.py:26-36 — a non-empty docker_image makes
        # harbor PULL instead of build, unless force_build is set (we never
        # set it), and the Dockerfile's presence is then irrelevant. Upstream
        # builds its .sif once into POST_TRAIN_BENCH_CONTAINERS_DIR and every
        # job reuses it (run_task.sh:249), so pulling a prebuilt image is
        # CLOSER to upstream than rebuilding per run, not further from it.
        # INSIDE the section, not above it. Emitting this before the header
        # put it in whatever section preceded — [metadata] — where harbor
        # never looks, so docker_image read as None and it rebuilt from the
        # Dockerfile anyway. That silently wasted a full 38-minute run.
        img = f'\ndocker_image = "{image}"' if image else ""
        return f"""[{indent_header}]{img}
network_mode = "public"
build_timeout_sec = 3600.0
os = "linux"
cpus = {cpus}
memory_mb = {memory_mb}
storage_mb = {storage_mb}
gpus = {cfg.REQUEST_GPUS}
gpu_types = {json.dumps(gpu_types)}
mcp_servers = []
"""

    agent_env = {
        # set_env_vars.sh:24 / .codex/config.toml
        "HF_HOME": cfg.SANDBOX_HF_HOME,
        # run_task.sh:236-237
        "VLLM_API_KEY": cfg.VLLM_API_KEY,
        "PYTHONNOUSERSITE": "1",
        # agents/claude/solve.sh:5 -- `export BASH_MAX_TIMEOUT_MS="36000000"`,
        # i.e. exactly the 10 h agent budget.
        #
        # This is the ceiling on how long ONE Bash tool call may block before
        # Claude Code kills the command and hands control back to the model.
        # It is NOT the session timeout: the session cap ends the whole run,
        # this ends a single command. Left at the CLI default (minutes), a
        # multi-hour `python train.py` gets killed mid-training and the model's
        # only recourse is to background the job and poll -- which is precisely
        # how a run ends with training still in flight, no final_model/, and
        # collect.py substituting the zero-shot baseline.
        #
        # The original pairs this with the non-interactive clause: the timeout
        # removes the need to background anything, the clause is the backstop.
        # We shipped the backstop without the fix until 2026-09-03.
        #
        # Set for every harness, not just Claude. It is a Claude Code variable
        # and the others ignore it, so gating it would add a branch with no
        # observable effect.
        "BASH_MAX_TIMEOUT_MS": "36000000",
        # D229. The exeunit exposes EVERY GPU on the node -- /dev/nvidia0 to
        # /dev/nvidia7 -- even though the task declares gpus = 1. check_cuda.py
        # fails its first branch (`device_count != NUM_GPUS`, 8 != 1), touches
        # cuda_not_available and exits 1; preflight.sh is the healthcheck, so
        # Harbor retries three times and aborts the trial with
        # HealthcheckError. That killed 8/8 runs of the 2026-09-04 sanity
        # sweep at t=86 s, across all three harnesses.
        #
        # Pinning to device 0 makes torch.cuda.device_count() == 1, so
        # check_cuda.py passes COMPLETELY UNMODIFIED -- the deviation is this
        # one variable, not a patch to the original's gate.
        #
        # "0" is not "physical GPU 0". The NVIDIA container runtime renumbers
        # per container, so index 0 always means "the first GPU this container
        # was given". That keeps the value correct if the platform later packs
        # one task per GPU: the task's assigned device is its index 0, and no
        # re-push is needed.
        #
        # ⚠️ Relaxing check_cuda.py instead (>= 1, or deleting it) is NOT
        # equivalent and is actively unsafe: the check is an assertion, not a
        # mechanism. All 8 devices would stay visible and HF Trainer defaults
        # to DataParallel across every visible GPU, silently training on 8 and
        # producing a score that cannot be compared with the leaderboard.
        "CUDA_VISIBLE_DEVICES": "0",
        "NUM_GPUS": str(cfg.REQUEST_GPUS),
        # read by preflight.sh when it invokes create_timer.sh
        "PTB_NUM_HOURS": str(num_hours),
        # read by preflight.sh, which links the read-only cache mount back
        # under HF_HOME one repo at a time. Upstream needs no equivalent: its
        # cache arrives as a fuse-overlayfs bound straight onto HF_HOME.
        "PTB_HF_CACHE_MOUNT": ":".join(hf_cache_mounts),
    }
    # run_task.sh:83-85 + the info.json half of the allowlist: OPENAI_API_KEY
    # reaches the agent only on the benchmarks whose grading needs it.
    for key in required_keys:
        agent_env[key] = "${" + key + "}"
    # DIVERGENCE, and forced. Upstream hands the agent a real OpenAI key, so
    # arenahardwriting/healthbench grading reaches api.openai.com with no base
    # URL. Kaggle's key is a *model-proxy* key (entrypoint-common.sh:313-314),
    # and both benchmarks' evaluate.py grade through a bare `openai.OpenAI()`,
    # which reads OPENAI_BASE_URL from the environment. Without this the two
    # LLM-judged benchmarks dial the public endpoint and 401 — inside the
    # agent's own loop, where it looks like a task failure rather than a
    # misconfiguration. Same root cause as divergence 2 (codex needing
    # `-c openai_base_url=`); [verifier.env] already carries the pair.
    if "OPENAI_API_KEY" in required_keys:
        agent_env["OPENAI_BASE_URL"] = "${OPENAI_BASE_URL:-}"
        agent_env["PTB_JUDGE_MODEL"] = "openai/gpt-5-mini"
    # check_cuda.py:44 is `if "H100" in name`, so the gate fails on any other
    # device — and it runs as the healthcheck, which aborts the trial before
    # the agent starts (environments/base.py:1376-1380). Kaggle's only
    # accelerator pool is a single L4, so a real-image test run there needs
    # this off. Decoupled from --smoke on purpose: --smoke also swaps in
    # lightweight Dockerfiles, which is the opposite of what a "does the real
    # thing work end to end" run wants. Upstream's check_cuda.py is untouched;
    # this only sets the env var preflight.sh already honours.
    if smoke or skip_cuda_check:
        agent_env["PTB_SKIP_CUDA_CHECK"] = "1"

    verifier_env = {
        # The judges run codex against the model proxy. entrypoint-common.sh
        # exports OPENAI_API_KEY / OPENAI_BASE_URL in the executor from
        # MODEL_PROXY_*, and harbor resolves ${VAR} here against that env.
        "OPENAI_API_KEY": "${OPENAI_API_KEY}",
        # :- so a host without the var (a plain `harbor run`) resolves to
        # empty rather than failing task load; test.sh falls back to the
        # public OpenAI endpoint and reports the auth check result.
        "OPENAI_BASE_URL": "${OPENAI_BASE_URL:-}",
        # judge_lib.sh runs the codex CLI, which reads CODEX_API_KEY.
        "CODEX_API_KEY": "${OPENAI_API_KEY}",
        "PTB_JUDGE_MODEL": "openai/gpt-5-mini",
        "PYTHONNOUSERSITE": "1",
        "VLLM_API_KEY": cfg.VLLM_API_KEY,
        # D229, same reason as the agent side. The verifier requests its own
        # H100 and gets the same all-devices-visible container, and it is the
        # half that actually loads the trained model: evaluate.py starts a vLLM
        # server over whatever CUDA reports. The original evaluated on the one
        # GPU the job was given, so pin to one here too rather than leaving the
        # device count up to how many the node happens to have.
        "CUDA_VISIBLE_DEVICES": "0",
        # The model the platform actually scheduled. metadata.json's
        # agent_config is baked at build time and one task is shared by every
        # candidate (D228), so for any candidate but the first it names the
        # wrong model -- and get_judge_prompt.build_agent_harness_clause uses
        # it to tell the judges which model banners and usage records are the
        # harness rather than an agent-made API call. Empty when the platform
        # does not export it, in which case test.sh falls back to metadata.
        "KAGGLE_AGENT_LLM": "${KAGGLE_AGENT_LLM:-}",
    }
    # The read-only cache mount, put inside this container by the
    # tests/docker-compose.yaml stage_tests() writes (the only seam that reaches
    # a separate verifier env — see the comment there). test.sh links it into a
    # writable HF_HOME the same way preflight.sh does for the agent; it must NOT
    # become HF_HOME itself, because huggingface_hub writes locks under it.
    if hf_cache_mounts:
        verifier_env["PTB_HF_CACHE_MOUNT"] = ":".join(hf_cache_mounts)
    if smoke:
        verifier_env["PTB_ALLOW_MISSING_JUDGEMENTS"] = "1"

    def env_block(header: str, values: dict[str, str]) -> str:
        lines = [f"[{header}]"]
        for k, v in values.items():
            lines.append(f'{k} = "{v}"')
        return "\n".join(lines) + "\n"

    return f"""schema_version = "1.4"

[task]
name = "posttrainbench/{slug.removeprefix(cfg.TASK_SLUG_PREFIX + '-')}"
version = "1.0.0"
description = "Post-train {model_to_train} to maximise {benchmark_name}."
keywords = ["post-training", "llm", "fine-tuning", "gpu"]

[[task.authors]]
name = "PostTrainBench"

[metadata]
benchmark_id = "{benchmark_id}"
model_to_train = "{model_to_train}"
num_hours = {num_hours}
upstream = "https://github.com/aisa-group/PostTrainBench"
smoke_build = {str(smoke).lower()}
skip_cuda_check = {str(skip_cuda_check).lower()}

# Resources are single_task.sub's, verified identical across all nine submit
# files in src/commit_utils/: 16 CPUs, 128 GB RAM, 400 GB disk, one
# "NVIDIA H100 80GB HBM3". gpu_types cannot express the exact device string
# the HTCondor `requirements` line pins, so it asks for the family.
{resources("environment", docker_image)}
# run_task.sh:246-247 — the agent's home is /home/ben and its working
# directory /home/ben/task. Both are load-bearing on the prompt: rule 6
# points at the home folder for the HF cache, and the Decontamination Tool
# section references ../test_data.json.
workdir = "{cfg.SANDBOX_WORKDIR}"

{env_block("environment.env", agent_env)}
# The one hook harbor runs before the agent, and therefore where
# run_task.sh's pre-agent work has to live: the check_cuda gate, timer.sh
# generation and the system monitor. All retries must pass before agent
# setup begins, so a failing CUDA gate aborts the run — which is what
# `|| exit 1` does upstream.
[environment.healthcheck]
command = "bash /usr/local/bin/preflight.sh"
interval_sec = 10.0
timeout_sec = 180.0
start_period_sec = 15.0
start_interval_sec = 5.0
retries = 3

[agent]
# run_task.sh:225 wraps the agent in `timeout ... "$((NUM_HOURS * 60 + 5))m"`
# — the budget plus a five-minute grace period.
timeout_sec = {agent_timeout_sec}

[verifier]
# DIVERGENCE: upstream has no verifier-level cap. Its evaluation can run
# three phases of retries at `timeout 28800s` each (run_task.sh:441), so the
# ceiling is whatever the cluster allows. Harbor requires a number and the
# Kaggle session cap has to accommodate the agent budget as well, so this is
# a platform constraint rather than an upstream value. Override with
# --verifier-timeout-sec.
timeout_sec = {verifier_timeout_sec}
environment_mode = "separate"

{env_block("verifier.env", verifier_env)}
# Upstream runs the judges in gpt_5_5.sif and the evaluation in
# vllm_debug.sif, neither of them the agent's image. Same resources: the
# evaluation loads the model into vLLM, so it needs the same GPU.
{resources("verifier.environment", verifier_docker_image)}
# The agent sandbox home, carried into the verifier. Harbor re-materialises
# an artifact at its original source path, so /home/ben arrives as
# /home/ben — which is what test.sh, the judges and delete_hf_models.py all
# expect.
#
# NO `exclude`, and that is load-bearing. artifact_handler.py:335-347 branches
# on exactly that field: an entry with an exclude list goes through
# service_download_dir_with_exclusions, which shells `tar czf --exclude=...`
# under a hardcoded timeout_sec=120 (environments/base.py:991-995); an entry
# without one goes through service_download_dir, a plain `docker compose cp`
# with no tar, no gzip and no timeout (environments/docker/docker_unix.py:
# 190-200). Model weights are incompressible, so the capped path measured
# ~32 MB/s here — about 3.8 GB before the timer fires, against a bf16 4B
# `final_model` of ~8 GB. That failure lands *after* the full agent budget has
# been spent. The exclude existed only to keep the HF cache mount out of the
# copy; preflight.sh now links the cache in from PTB_HF_CACHE_MOUNT outside
# the home instead, and `docker cp` copies a symlink as a symlink (verified
# by A/B: 200 MB linked in copied 12 K in 0 s, the same 200 MB physically
# present copied 201 M).
[[artifacts]]
source = "{cfg.SANDBOX_HOME}"
destination = "home"

# The raw agent trace. run_task.sh:212 puts it at $EVAL_DIR/solve_out.txt and
# :250 fills it by redirecting the whole sandbox session there. Harbor owns
# the agent process instead and tees the same stream to
# /logs/agent/<harness>.txt (claude_code.py:1782-1783, codex.py:1448-1449,
# cursor_cli.py:883, gemini_cli.py:854, opencode.py:519). A separate verifier
# environment mounts only /logs/verifier (trial/trial.py:685-692), so the
# trace reaches test.sh the way everything else does — as an artifact,
# re-materialised at its original source path
# (trial/artifact_handler.py:61-63).
[[artifacts]]
source = "{cfg.AGENT_LOGS_DIR}"
"""


# ---------------------------------------------------------------------------
# one task
# ---------------------------------------------------------------------------

def generate_task(
    *,
    benchmark_id: str,
    model_to_train: str,
    agent: str,
    agent_config: str,
    num_hours: int,
    num_gpus: int,
    output_dir: Path,
    eval_script: str,
    judge_model_map: dict[str, str],
    agent_timeout_sec: float | None,
    verifier_timeout_sec: float,
    hf_cache_mounts: list[str],
    torch_backend: str,
    allow_missing_test_data: bool,
    skip_cuda_check: bool,
    docker_image: str | None,
    verifier_docker_image: str | None,
    verifier_base_image: str | None,
    agent_base_image: str | None,
    gpu_types: list[str],
    cpus: int,
    memory_mb: int,
    storage_mb: int,
    smoke: bool,
) -> Path:
    slug = cfg.task_slug(benchmark_id, model_to_train)
    task_dir = output_dir / slug
    if task_dir.exists():
        shutil.rmtree(task_dir)
    task_dir.mkdir(parents=True)

    benchmark_name = read_benchmark_name(benchmark_id)

    instruction = generate_instruction(
        benchmark_id, model_to_train, str(num_hours), PROMPT_AGENT, num_gpus
    )
    (task_dir / "instruction.md").write_text(instruction)

    stage_environment(task_dir, benchmark_id, eval_script, allow_missing_test_data,
                      torch_backend, docker_image, smoke, agent_base_image)

    metadata = {
        "benchmark_id": benchmark_id,
        "benchmark_name": benchmark_name,
        "model_to_train": model_to_train,
        "model_key": cfg.model_key(model_to_train),
        "agent": agent,
        "agent_config": agent_config,
        "num_hours": num_hours,
        "num_gpus": num_gpus,
        "eval_script": eval_script,
        # score_run.py's baseline fallback, from scripts/baselines.json.
        "zeroshot_baseline": cfg.zeroshot_baseline(benchmark_id, model_to_train),
        # scripts/factors.json — the weight this benchmark carries in the
        # overall metric (aggregate.py:compute_weighted_metric). Not used by
        # the verifier; recorded so the Kaggle parent mapping can be built
        # from the task rather than from a second copy of the table.
        "benchmark_weight": cfg.load_factors()[benchmark_id],
        "smoke_build": smoke,
        "skip_cuda_check": skip_cuda_check,
        "docker_image": docker_image,
        "verifier_docker_image": verifier_docker_image,
        "verifier_base_image": verifier_base_image,
        "gpu_types": gpu_types,
        "cpus": cpus,
        "memory_mb": memory_mb,
        "storage_mb": storage_mb,
    }

    stage_tests(
        task_dir, benchmark_id, model_to_train, agent, agent_config,
        judge_model_map, metadata, hf_cache_mounts, torch_backend,
        verifier_docker_image, verifier_base_image, smoke,
    )

    if agent_timeout_sec is None:
        agent_timeout_sec = float(
            (num_hours * 60 + cfg.AGENT_GRACE_MINUTES) * 60
        )

    (task_dir / "task.toml").write_text(
        render_task_toml(
            slug=slug,
            benchmark_id=benchmark_id,
            benchmark_name=benchmark_name,
            model_to_train=model_to_train,
            num_hours=num_hours,
            agent_timeout_sec=agent_timeout_sec,
            verifier_timeout_sec=verifier_timeout_sec,
            hf_cache_mounts=hf_cache_mounts,
            skip_cuda_check=skip_cuda_check,
            docker_image=docker_image,
            agent_base_image=agent_base_image,
            verifier_docker_image=verifier_docker_image,
            gpu_types=gpu_types,
            cpus=cpus,
            memory_mb=memory_mb,
            storage_mb=storage_mb,
            smoke=smoke,
        )
    )
    return task_dir


# ---------------------------------------------------------------------------
# cli
# ---------------------------------------------------------------------------

DEFAULT_JUDGE_MODEL_MAP = {
    # judge_lib.sh's JUDGE_DEFAULT_MODEL and general_judge/judge.conf's
    # JUDGE_MODEL are bare upstream names. The Kaggle model proxy serves
    # dated slugs, so they are remapped here.
    #
    # The targets must be RESPONSES-wired slugs, not merely valid ones. The
    # proxy picks its backend from the slug, not from the shape of the
    # request (harbor says so itself at
    # container/harbor-base/entrypoint-common.sh:509-518), and codex speaks
    # only the Responses API. A Responses call against a Chat-Completions-wired
    # slug crosses the FE/BE mismatch in b/544507744 and comes back
    # contaminated rather than as a clean 4xx. Confirmed by the model-proxy
    # team on 2026-09-01, and independently re-confirmed.
    #
    # Measured against the live catalog (GET $MODEL_PROXY_URL, 2026-09-01,
    # 145 models):
    #   openai/gpt-5.4-responses      ABSENT  <- marvin named it; it does not exist
    #   openai/gpt-5.5-responses      present
    #   openai/gpt-5.6-sol-responses  present
    #   openai/gpt-5.6-terra          present, and so is openai/gpt-5.6-terra-cc
    #
    # The `-cc` sibling is what makes the terra mapping safe: the bare 5.6
    # slug is the Responses one and `-cc` is the Chat-Completions variant, so
    # upstream's own `gpt-5.6-terra` needs no substitution.
    #
    # gpt-5.4 STAYS gpt-5.4: the project permits gpt-5.4 and gpt-5.6 only,
    # not gpt-5.5 (2026-09-01). Substituting gpt-5.5-responses was briefly
    # written here and reverted — it is a different model generation, which
    # the `-2026-03-05` mapping was not, and the measurement does not support
    # paying that cost: prod run 867385 ran codex against
    # `openai/gpt-5.4-2026-03-05` over the proxy's Responses endpoint and got
    # a clean `turn.completed` with the correct answer. The FE/BE mismatch in
    # b/544507744 did not appear on that turn.
    #
    # ⚠️ What that run does NOT prove: it was a one-shot "reply with PONG".
    # A judge turn is multi-turn and tool-heavy, which is where a contaminated
    # stream would actually bite. Treat gpt-5.4 as UNPROVEN for judge-shaped
    # work until a real judge completes on it.
    #
    # If it does turn out to be contaminated, the fidelity-preserving fix is
    # for the model-proxy team to add `openai/gpt-5.4-responses` (it does NOT
    # exist today — checked against the live 145-model catalog on 2026-09-01).
    # Substituting another generation is a last resort and needs sign-off.
    "gpt-5.4": "openai/gpt-5.4-2026-03-05",
    "gpt-5.6-terra": "openai/gpt-5.6-terra",
}


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--all", action="store_true", help="Generate all 28 cells.")
    p.add_argument("--benchmark", action="append", choices=cfg.BENCHMARKS)
    p.add_argument("--model", action="append", choices=cfg.MODELS)
    p.add_argument(
        "--agent", required=True,
        help="Upstream agent name — the agents/<name>/ directory, e.g. "
             "claude, codex, cursor_cli, gemini, opencode. Recorded in "
             "metadata.json, where test.sh reads it back as run_task.sh's "
             "${AGENT} for get_judge_prompt.py and parse_trace.py. It is NOT "
             "what reaches get_prompt.py: see PROMPT_AGENT.",
    )
    p.add_argument(
        "--agent-config", default="",
        help="Agent harness model, e.g. gpt-5.1-codex-max. Used by the API "
             "usage and general judges to describe the harness identity they "
             "must not mistake for an agent-made API call "
             "(get_judge_prompt.py:build_agent_harness_clause).",
    )
    p.add_argument("--num-hours", type=int, default=cfg.DEFAULT_NUM_HOURS)
    p.add_argument("--num-gpus", type=int, default=cfg.REQUEST_GPUS)
    p.add_argument("--output", type=Path, required=True)
    p.add_argument(
        "--judge-backend", choices=("openai", "openrouter"), default="openai",
        help="Which eval script the agent's workspace gets. run_task.sh:16-26 "
             "picks this at run time; the agent's copy has to be baked in, so "
             "the same default (openai) is used. test.sh keeps the runtime "
             "logic for its own invocation.",
    )
    p.add_argument(
        "--verifier-timeout-sec", type=float, default=7200.0,
        help="Harbor requires a verifier cap; upstream has none. See the "
             "comment this writes into task.toml.",
    )
    p.add_argument(
        "--agent-timeout-sec", type=float, default=None,
        help="Override the agent timeout. Default is upstream's "
             "(num_hours * 60 + 5) minutes. Set this for a fast smoke run "
             "without changing num_hours, which the prompt and timer read.",
    )
    p.add_argument(
        "--hf-cache", default=cfg.HF_CACHE_MOUNT,
        help="Comma-separated container paths the read-only HuggingFace cache "
             "datasets are mounted at. The cache ships as several Kaggle "
             "datasets because ~396 HF repos unpack to well over the 1,000 "
             "files one dataset allows without ExtraDatasetsQuota; each shard "
             "carries the same $HF_HOME layout and preflight.sh merges them "
             "into /home/ben/hf_cache, which stays the agent-visible HF_HOME "
             "per set_env_vars.sh:23. They must sit outside /home/ben so the "
             "sandbox-home artifact does not try to copy the cache.",
    )
    p.add_argument(
        "--torch-backend", default="auto",
        help="Value for the TORCH_BACKEND build arg both Dockerfiles pass to "
             "`uv pip install vllm --torch-backend=`. Upstream hardcodes "
             "`auto` (containers/standard.def:34, vllm_debug.def:34) so that "
             "is the faithful default; `auto` probes the NVIDIA driver and "
             "resolves to CPU torch on a builder without one, which then "
             "fails vllm's CUDA-only xformers dependency. Pass cu128 if the "
             "image builder turns out to have no GPU.",
    )
    p.add_argument(
        "--docker-image", default=None,
        help="Prebuilt agent image, e.g. us-west1-docker.pkg.dev/.../ptb-agent:v1. "
             "Harbor then PULLS instead of building (definition.py:26-36), "
             "turning a ~1h CUDA build into seconds. force_build is never set, "
             "so the Dockerfile can stay in the tree as documentation.",
    )
    p.add_argument(
        "--verifier-docker-image", default=None,
        help="Prebuilt verifier image, used AS IS. ⚠️ Its baked /tests wins "
             "for every task -- harbor skips the tests upload for a separate "
             "verifier env -- so one image across many tasks means one "
             "benchmark's tests for all of them. Prefer --verifier-base-image.",
    )
    p.add_argument(
        "--verifier-base-image", default=None,
        help="Prebuilt base carrying only the heavy layers. Each task then "
             "BUILDS its verifier as FROM <base> + its own tests/, which is "
             "the only way per-task /tests reaches a separate verifier env.",
    )
    p.add_argument(
        "--agent-base-image", default=None,
        help="Prebuilt AGENT base, e.g. .../ptb-agent:v3. Each task then "
             "builds a thin layer on it that COPYs its own home/ into "
             "/home/ben. Use this INSTEAD of --docker-image: a prebuilt "
             "docker_image makes harbor pull and never build, so the task's "
             "own evaluate.py/test_data.json never reach the agent and it "
             "sees whatever the base was built with (gsm8k). See "
             "template/environment/Dockerfile.perTask.",
    )
    p.add_argument(
        "--gpu-types", default=",".join(cfg.GPU_TYPES),
        help="Override [environment] gpu_types. Default is single_task.sub's "
             "H100, which the push API rejects: it accepts only l4, nvidia-l4, "
             "a100, a100-40gb, nvidia-tesla-a100. Note A100 IS offered — the "
             "L4 pool is not the only option.",
    )
    p.add_argument(
        "--cpus", type=int, default=cfg.REQUEST_CPUS,
        help="Override [environment] cpus. Default is single_task.sub's 16. "
             "Without large-container access the push API caps this at 4.",
    )
    p.add_argument(
        "--memory-mb", type=int, default=cfg.REQUEST_MEMORY_MB,
        help="Override [environment] memory_mb. Default is single_task.sub's "
             "131072; the push API rejects anything above 62464, and without "
             "large-container access caps it at 30720. Lower it only for "
             "platform-validation runs.",
    )
    p.add_argument(
        "--storage-mb", type=int, default=cfg.REQUEST_DISK_MB,
        help="Override [environment] storage_mb. Default is single_task.sub's "
             "409600; the push API caps it at 221184, and at 81920 without "
             "large-container access. Same caveat as --memory-mb.",
    )
    p.add_argument(
        "--skip-cuda-check", action="store_true",
        help="Disable the H100 gate while keeping the REAL images. "
             "check_cuda.py:44 hard-requires an H100 and runs as the "
             "healthcheck, so a real-image run on Kaggle's L4 pool cannot "
             "start without this. For pipeline validation only — the "
             "resulting numbers are not comparable to the published "
             "benchmark. Stamped into task.toml [metadata] and "
             "tests/metadata.json.",
    )
    p.add_argument("--allow-missing-test-data", action="store_true")
    p.add_argument(
        "--smoke", action="store_true",
        help="Mark the build as a smoke test: skips the CUDA gate and lets "
             "score_run.py score a run with missing judge verdicts. Stamped "
             "into task.toml [metadata] and tests/metadata.json so a smoke "
             "task is never mistaken for a real one.",
    )
    args = p.parse_args()

    if args.all:
        benchmarks, models = cfg.BENCHMARKS, cfg.MODELS
    else:
        benchmarks = args.benchmark or []
        models = args.model or []
        if not benchmarks or not models:
            p.error("pass --all, or at least one --benchmark and one --model")

    hf_cache_mounts = [m.strip() for m in (args.hf_cache or "").split(",") if m.strip()]

    args.output.mkdir(parents=True, exist_ok=True)

    # The custom-import agent package. harbor_apply_custom_import_pythonpath
    # (container/harbor-base/entrypoint-common.sh:531-541) prepends
    # KAGGLE_TASK_DEFINITION_ROOT — the task-definition mount root, i.e. this
    # output directory — to PYTHONPATH, so `--agent agents.ptb_harness:...`
    # resolves only if the package sits here, beside the task directories.
    # Same layout as kaggle-benchmark-harbor-starter-template/agents/.
    agents_dst = args.output / "agents"
    if agents_dst.exists():
        shutil.rmtree(agents_dst)
    _copy(Path(__file__).resolve().parent / "agents", agents_dst)
    shutil.rmtree(agents_dst / "__pycache__", ignore_errors=True)
    print(f"staged {agents_dst}")

    eval_script = (
        "evaluate_openrouter.py" if args.judge_backend == "openrouter"
        else "evaluate.py"
    )

    built = []
    for benchmark_id in benchmarks:
        for model_to_train in models:
            task_dir = generate_task(
                benchmark_id=benchmark_id,
                model_to_train=model_to_train,
                agent=args.agent,
                agent_config=args.agent_config,
                num_hours=args.num_hours,
                num_gpus=args.num_gpus,
                output_dir=args.output,
                eval_script=eval_script,
                judge_model_map=DEFAULT_JUDGE_MODEL_MAP,
                agent_timeout_sec=args.agent_timeout_sec,
                verifier_timeout_sec=args.verifier_timeout_sec,
                hf_cache_mounts=hf_cache_mounts,
                torch_backend=args.torch_backend,
                allow_missing_test_data=args.allow_missing_test_data,
                skip_cuda_check=args.skip_cuda_check,
                docker_image=args.docker_image,
                verifier_docker_image=args.verifier_docker_image,
                verifier_base_image=args.verifier_base_image,
                agent_base_image=args.agent_base_image,
                gpu_types=[g.strip() for g in args.gpu_types.split(',') if g.strip()],
                cpus=args.cpus,
                memory_mb=args.memory_mb,
                storage_mb=args.storage_mb,
                smoke=args.smoke,
            )
            built.append(task_dir)
            print(f"generated {task_dir}")

    print(f"\n{len(built)} task(s) in {args.output}")
    if args.smoke:
        print("SMOKE BUILD — CUDA gate disabled, missing judge verdicts tolerated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
