#!/usr/bin/env python3
"""Check that the generated tasks still match upstream.

"1:1 with the original" is only worth something if it is testable, so this
asserts it rather than documenting it. Three kinds of check:

  A. Constants — every value transcribed into config.py is re-derived from
     the upstream file it came from (commit.sh, run_task.sh, single_task.sub,
     judge_lib.sh) and compared. Catches upstream drifting away from the
     port.

  B. Copied files — every file staged into a task is byte-compared with its
     source in the checkout. Catches accidental edits to a copy.

  C. Generated prompts — instruction.md is regenerated by running
     get_prompt.py and diffed. Catches any divergence in the one artifact
     the agent actually reads.

Plus task.toml parsing through harbor's own model, so a schema mistake is
caught here and not on the platform.

    python src/kaggle_harbor/verify_fidelity.py --tasks ./tasks
"""

from __future__ import annotations

import argparse
import filecmp
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import config as cfg  # noqa: E402
import build_tasks  # noqa: E402

REPO_ROOT = cfg.REPO_ROOT

# parse_trace.py:20-25 imports its parsers as flat siblings, which works for a
# script because python puts its directory on sys.path. Importing it as a
# module needs the same entry.
sys.path.insert(0, str(REPO_ROOT / "src" / "trace_parsing"))

import parse_trace  # noqa: E402
from agents import ptb_harness  # noqa: E402

failures: list[str] = []
checks = 0


def check(condition: bool, message: str) -> None:
    global checks
    checks += 1
    if not condition:
        failures.append(message)


def check_eq(actual, expected, what: str) -> None:
    check(actual == expected, f"{what}\n     upstream: {expected!r}\n     port:     {actual!r}")


# ---------------------------------------------------------------------------
# A. constants
# ---------------------------------------------------------------------------

def verify_constants() -> None:
    print("A. constants re-derived from upstream")

    # --- the matrix, from commit.sh -----------------------------------------
    commit = (REPO_ROOT / "src" / "commit_utils" / "commit.sh").read_text()

    def bash_array(name: str) -> list[str]:
        m = re.search(rf"^{name}=\(\s*(.*?)\s*\)\s*$", commit, re.M | re.S)
        if not m:
            raise AssertionError(f"no {name}=( ... ) array in commit.sh")
        body = "\n".join(
            line.split("#", 1)[0] for line in m.group(1).splitlines()
        )
        return re.findall(r'"([^"]+)"', body)

    check_eq(cfg.MODELS, bash_array("models"), "commit.sh models[]")
    check_eq(cfg.BENCHMARKS, bash_array("evals"), "commit.sh evals[]")
    print(f"   models   {len(cfg.MODELS)}  evals {len(cfg.BENCHMARKS)}"
          f"  -> {len(cfg.MODELS) * len(cfg.BENCHMARKS)} cells")

    # --- resources, from every submit file ----------------------------------
    sub_dir = REPO_ROOT / "src" / "commit_utils"
    subs = sorted(sub_dir.rglob("*.sub"))
    check(len(subs) > 0, "no .sub files found under src/commit_utils")
    for sub in subs:
        text = sub.read_text()
        rel = sub.relative_to(REPO_ROOT)

        def val(key: str) -> str | None:
            m = re.search(rf"^\s*{key}\s*=\s*(\S+)", text, re.M)
            return m.group(1) if m else None

        # The baselines/ submit files describe zero-shot baseline jobs, which
        # scripts/utils.py excludes from the sweep (SKIP_METHODS) and which
        # are out of scope for this port.
        if "baselines" in str(rel):
            continue
        if val("request_cpus"):
            check_eq(int(val("request_cpus")), cfg.REQUEST_CPUS, f"{rel} request_cpus")
        if val("request_memory"):
            check_eq(int(val("request_memory")), cfg.REQUEST_MEMORY_MB, f"{rel} request_memory")
        # request_gpus is `$(num_gpus)`, a submit-file macro defaulted at the
        # top of the file and overridable per job with `-a num_gpus=`.
        # Compare against the default.
        gpus_raw = val("request_gpus")
        if gpus_raw:
            if gpus_raw.startswith("$("):
                macro = re.search(
                    rf"^\s*{re.escape(gpus_raw[2:-1])}\s*=\s*(\d+)", text, re.M
                )
                check(macro is not None, f"{rel} request_gpus macro {gpus_raw} has no default")
                if macro:
                    check_eq(int(macro.group(1)), cfg.REQUEST_GPUS, f"{rel} request_gpus default")
            else:
                check_eq(int(gpus_raw), cfg.REQUEST_GPUS, f"{rel} request_gpus")
        if val("request_disk"):
            disk = val("request_disk").upper().rstrip("G")
            check_eq(int(disk) * 1024, cfg.REQUEST_DISK_MB, f"{rel} request_disk")
        if "CUDADeviceName" in text:
            check("H100" in text, f"{rel} no longer pins an H100")
    print(f"   {len(subs)} submit file(s) agree on cpus/memory/disk/gpus/H100")

    # --- eval retry schedule, from run_task.sh ------------------------------
    run_task = (REPO_ROOT / "src" / "run_task.sh").read_text()

    retries = [
        int(m) for m in re.findall(r"^run_evaluation_with_retry (\d+)", run_task, re.M)
    ]
    check_eq(tuple(retries), cfg.EVAL_PHASE_RETRIES, "run_task.sh retry schedule")

    timeout = re.search(r"--kill-after=60s (\d+)s", run_task)
    check_eq(int(timeout.group(1)), cfg.EVAL_ATTEMPT_TIMEOUT_SEC,
             "run_task.sh per-attempt eval timeout")

    # The two `case "${EVALUATION_TASK}"` blocks that set MAX_TOKENS_ARG, in
    # source order: phase 2 then phase 3.
    blocks = re.findall(
        r'case "\$\{EVALUATION_TASK\}" in\n(.*?)\nesac', run_task, re.S
    )
    check(len(blocks) == 2, f"expected 2 MAX_TOKENS case blocks, found {len(blocks)}")
    if len(blocks) == 2:
        for block, expected, label in zip(
            blocks, (cfg.MAX_TOKENS_PHASE2, cfg.MAX_TOKENS_PHASE3), ("phase2", "phase3")
        ):
            parsed = dict(
                re.findall(r"(\w+)\)\s*\n\s*MAX_TOKENS_ARG=\"([^\"]*)\"", block)
            )
            parsed.pop("*", None)
            check_eq(parsed, expected, f"run_task.sh MAX_TOKENS {label}")
    print("   run_task.sh retry counts, attempt timeout and both token tables match")

    # --- grace period -------------------------------------------------------
    grace = re.search(r'"\$\(\(NUM_HOURS \* 60 \+ (\d+)\)\)m"', run_task)
    check_eq(int(grace.group(1)), cfg.AGENT_GRACE_MINUTES, "run_task.sh agent grace minutes")

    # --- sandbox layout -----------------------------------------------------
    check(f'--home "${{JOB_DIR}}:{cfg.SANDBOX_HOME}"' in run_task,
          f"run_task.sh no longer mounts the home at {cfg.SANDBOX_HOME}")
    check(f'--pwd "{cfg.SANDBOX_WORKDIR}"' in run_task,
          f"run_task.sh no longer uses {cfg.SANDBOX_WORKDIR} as the working dir")

    set_env = (REPO_ROOT / "src" / "commit_utils" / "set_env_vars.sh").read_text()
    m = re.search(r'export HF_HOME_NEW="([^"]+)"', set_env)
    check_eq(m.group(1), cfg.SANDBOX_HF_HOME, "set_env_vars.sh HF_HOME_NEW")
    print("   sandbox home, working dir and HF_HOME match")

    # --- judges, from judge_lib.sh ------------------------------------------
    judge_lib = (REPO_ROOT / "src" / "judges" / "judge_lib.sh").read_text()
    m = re.search(r"^ALL_JUDGES=\(([^)]*)\)", judge_lib, re.M)
    check_eq(m.group(1).split(), cfg.ALL_JUDGES, "judge_lib.sh ALL_JUDGES")
    m = re.search(r'JUDGE_DEFAULT_MODEL="([^"]+)"', judge_lib)
    check_eq(m.group(1), cfg.JUDGE_DEFAULT_MODEL, "judge_lib.sh JUDGE_DEFAULT_MODEL")
    m = re.search(r'JUDGE_DEFAULT_REASONING_EFFORT="([^"]+)"', judge_lib)
    check_eq(m.group(1), cfg.JUDGE_DEFAULT_REASONING_EFFORT,
             "judge_lib.sh JUDGE_DEFAULT_REASONING_EFFORT")
    print(f"   {len(cfg.ALL_JUDGES)} judges, default model and effort match")

    # --- container pins, from the .def files --------------------------------
    standard = (REPO_ROOT / "containers" / "standard.def").read_text()
    check(f"vllm=={cfg.VLLM_VERSION}" in standard, "standard.def vllm pin")
    check(f"flash-attn=={cfg.FLASH_ATTN_VERSION}" in standard, "standard.def flash-attn pin")
    check(cfg.INSPECT_EVALS_COMMIT in standard, "standard.def inspect_evals commit")
    check(f"@openai/codex@{cfg.AGENT_CODEX_VERSION}" in standard, "standard.def codex pin")
    check(cfg.BASE_IMAGE in standard, "standard.def base image")

    gpt55 = (REPO_ROOT / "containers" / "gpt_5_5.def").read_text()
    check(f"@openai/codex@{cfg.VERIFIER_CODEX_VERSION}" in gpt55, "gpt_5_5.def codex pin")

    general_conf = (REPO_ROOT / "src" / "judges" / "general_judge" / "judge.conf").read_text()
    check(f'JUDGE_CODEX_VERSION="{cfg.GENERAL_JUDGE_CODEX_VERSION}"' in general_conf,
          "general_judge JUDGE_CODEX_VERSION")
    print("   container package pins match standard.def / gpt_5_5.def")

    # --- the two Dockerfiles are transcriptions of the .def files -----------
    # Not a byte diff (different formats); check that every pinned version in
    # the .def also appears in the Dockerfile that ports it.
    tmpl = build_tasks.TEMPLATE_DIR
    agent_df = (tmpl / "environment" / "Dockerfile").read_text()
    verif_df = (tmpl / "tests" / "Dockerfile").read_text()
    for token in (cfg.BASE_IMAGE, f"vllm=={cfg.VLLM_VERSION}",
                  f"flash-attn=={cfg.FLASH_ATTN_VERSION}", cfg.INSPECT_EVALS_COMMIT):
        check(token in agent_df, f"environment/Dockerfile missing {token}")
        check(token in verif_df, f"tests/Dockerfile missing {token}")
    check(f"@openai/codex@{cfg.AGENT_CODEX_VERSION}" in agent_df,
          "environment/Dockerfile codex pin drifted from standard.def")
    # D227: the verifier's codex is DELIBERATELY 0.146.1, not gpt_5_5.def's
    # 0.124.0. 0.124.0 has no HTTPS fallback, so the model proxy's 307 on the
    # websocket upgrade is fatal to it and test.sh had to inject a whole custom
    # model_providers block to work around it. 0.146.1 is the version Kaggle
    # registers as its canonical codex harness and falls back cleanly, so the
    # judges run stock configuration. One deviation traded for a smaller one.
    check("@openai/codex@0.146.1" in verif_df,
          "tests/Dockerfile codex pin is not 0.146.1 (D227)")

    # Every npm pin in gpt_5_5.def, not just codex. The verifier image is the
    # union of gpt_5_5.def and vllm_debug.def (D90), and the merge takes
    # gpt_5_5's pins (D91). An earlier revision installed codex alone because
    # it is the only CLI the verifier invokes; that was an efficiency argument
    # and it is not a reason to diverge, so all four ship (D92). Re-derived
    # from upstream here so dropping one again fails the check.
    gpt55 = (REPO_ROOT / "containers" / "gpt_5_5.def").read_text()
    npm_pins = re.findall(r"(@?[\w./@-]+@[\d.]+)\s*\\?\s*$", gpt55, re.MULTILINE)
    npm_pins = [p for p in npm_pins if "/" in p or p.startswith("opencode")]
    check(len(npm_pins) == 4,
          f"expected 4 npm pins in gpt_5_5.def, parsed {len(npm_pins)}: {npm_pins}")
    for pin in npm_pins:
        # codex is exempt: D227 pins it forward to 0.146.1. Every OTHER pin
        # must still match gpt_5_5.def exactly, so dropping one still fails.
        if pin.startswith("@openai/codex@"):
            check(pin == "@openai/codex@0.124.0",
                  f"gpt_5_5.def's codex pin moved to {pin}; D227 assumed 0.124.0 "
                  f"and its reasoning (no HTTPS fallback) should be rechecked")
            continue
        check(pin in verif_df,
              f"tests/Dockerfile is missing gpt_5_5.def's npm pin {pin} — "
              f"the union must install all four CLIs, not only the one it uses")
    vllm_debug = (REPO_ROOT / "containers" / "vllm_debug.def").read_text()
    check("inspect_ai_vllm_stdout" in vllm_debug and "inspect_ai_vllm_stdout" in verif_df,
          "tests/Dockerfile missing inspect_ai_vllm_stdout from vllm_debug.def")

    # --- scoring tables -----------------------------------------------------
    factors = cfg.load_factors()
    check_eq(sorted(factors), sorted(cfg.BENCHMARKS), "factors.json covers the benchmarks")
    total = sum(factors.values())
    check(abs(total - 1.0) < 1e-6,
          f"factors.json weights sum to {total}, not 1.0 — the root aggregation "
          f"is a weighted average and assumes they do")
    baselines = cfg.load_baselines()["zeroshot"]
    for model in cfg.MODELS:
        key = cfg.model_key(model)
        check(key in baselines, f"baselines.json has no zeroshot entry for {key}")
        for bench in cfg.BENCHMARKS:
            check(bench in baselines.get(key, {}),
                  f"baselines.json zeroshot[{key}] missing {bench}")
    print(f"   factors.json sums to {total:.6f}; baselines cover all 28 cells")


# ---------------------------------------------------------------------------
# A2. the custom-import harness wrappers
# ---------------------------------------------------------------------------

def verify_agent_wrapper(tasks_root: Path) -> None:
    """agents/ptb_harness.py against the two upstream dispatchers it feeds.

    The `--agent` string is read by get_prompt.py:120 ('claude' substring) and
    by parse_trace.py:36-44 (substring match against five parser keys, hard
    error on more than one, silent raw copy on none). The slug the platform
    passes through as KAGGLE_AGENT_HARNESS is one string for both, so both are
    asserted here.
    """
    print("\nA2. custom-import harness wrappers")

    # The clause literal, against get_prompt.py's own source.
    text = (REPO_ROOT / "src" / "eval" / "general" / "get_prompt.py").read_text(
        encoding="utf-8"
    )
    marker = '        result += """'
    start = text.index(marker) + len(marker)
    check_eq(ptb_harness._NON_INTERACTIVE_CLAUSE, text[start:text.index('"""', start)],
             "ptb_harness._NON_INTERACTIVE_CLAUSE vs get_prompt.py:121-123")

    wrappers = [
        ("PtbHarness_claude", "claude", "claude"),
        ("PtbHarness_codex", "codex", "codex"),
        ("PtbHarness_gemini", "gemini", "gemini"),
        ("PtbHarness_opencode", "opencode", "opencode"),
    ]
    for class_name, upstream_agent, parser_key in wrappers:
        cls = getattr(ptb_harness, class_name, None)
        check(cls is not None, f"agents/ptb_harness.py has no {class_name}")
        if cls is None:
            continue
        check_eq(cls.PTB_AGENT_NAME, upstream_agent, f"{class_name}.PTB_AGENT_NAME")

        slug = f"agents.ptb_harness:{class_name}"
        matches = [key for key in parse_trace.PARSERS if key in slug]
        check_eq(matches, [parser_key], f"parse_trace keys matched by {slug}")
        check_eq("claude" in slug, "claude" in upstream_agent,
                 f"get_prompt.py:120's rule on {slug} vs upstream name")

        # harbor/utils/import_path.py:29 — the machinery `--agent` uses.
        from harbor.agents.base import BaseAgent
        from harbor.utils.import_path import import_class
        try:
            check(import_class(slug, base=BaseAgent, label="agent") is cls,
                  f"{slug} does not resolve to {class_name}")
        except Exception as exc:  # noqa: BLE001
            check(False, f"{slug} failed to import: {exc}")

    # The staged copy the executor actually imports.
    staged = tasks_root / "agents"
    for name in ("__init__.py", "ptb_harness.py"):
        src = Path(__file__).resolve().parent / "agents" / name
        dst = staged / name
        check(dst.exists(), f"agents/{name} not staged at {staged}")
        if dst.exists():
            check(filecmp.cmp(dst, src, shallow=False),
                  f"staged agents/{name} differs from src/kaggle_harbor/agents/{name}")
    check(not (staged / "__pycache__").exists(),
          f"{staged}/__pycache__ was staged")

    # --- the CLI version each harness runs ---------------------------------
    # Upstream floats every agent CLI to @latest: each agents/<a>/solve.sh
    # opens with `update_agent_cli.sh <cli>`, which npm-installs `<pkg>@latest`
    # ahead of the baked copy, and the opt-out is commented out in example.env.
    # So the port must float too. Left unpinned, harbor SKIPS the install when
    # any build is already present, which would freeze all four at the
    # standard.def fallback — that is what made a gpt-5.6-sol run die on
    # `unknown variant 'max'`. Re-derived from upstream so a regression here
    # fails rather than silently pinning.
    for agent_dir in ("claude", "codex", "gemini", "opencode"):
        solve = REPO_ROOT / "agents" / agent_dir / "solve.sh"
        if solve.exists():
            check("update_agent_cli.sh" in solve.read_text(),
                  f"upstream agents/{agent_dir}/solve.sh no longer auto-updates "
                  f"its CLI — PTB_DEFAULT_VERSION='latest' may no longer be right")
    example_env = (REPO_ROOT / "example.env").read_text()
    check(not re.search(r"^\s*POST_TRAIN_BENCH_SKIP_CLI_UPDATE\s*=",
                        example_env, re.MULTILINE),
          "upstream example.env now SETS POST_TRAIN_BENCH_SKIP_CLI_UPDATE, so "
          "upstream pins its CLIs and PTB_DEFAULT_VERSION='latest' is wrong")
    # DELIBERATE DEVIATION, 2026-09-03, at the user's instruction: each harness
    # is pinned to the version Kaggle has REGISTERED for it, rather than
    # floating to @latest the way upstream's update_agent_cli.sh does.
    #
    # The two checks above still run, because they guard the reasoning behind
    # the original choice: if upstream ever stops auto-updating, the tradeoff
    # being made here changes and someone should notice.
    #
    # What is asserted now is that NOTHING is pinned. The agent slug names its
    # build and the platform passes it through as `--ak version=`, which the
    # sweep's own logs confirm ("version pin '0.146.1' (--ak version=)"). A pin
    # in the port would be a second copy of that fact, maintained by hand and
    # read by nothing -- and the starter template does not keep one either
    # (opencode_binary_agent.py:91 is `@{version} if version else @latest`).
    #
    # A slug naming a build that does not exist is the platform's error to
    # report, not ours to pre-empt.
    for class_name, _upstream_agent, _parser_key in wrappers:
        cls = getattr(ptb_harness, class_name, None)
        if cls is None:
            continue
        check(cls.PTB_DEFAULT_VERSION == "latest",
              f"{class_name}.PTB_DEFAULT_VERSION is "
              f"{cls.PTB_DEFAULT_VERSION!r}; the port pins no CLI builds -- the "
              f"scheduled slug supplies the version")

    print(f"   {len(wrappers)} wrappers: clause literal, parser dispatch, "
          f"import path, staged copy, CLI pinned to the registered harness "
          f"version")


# ---------------------------------------------------------------------------
# B + C. per-task checks
# ---------------------------------------------------------------------------

def verify_task(task_dir: Path) -> None:
    meta = json.loads((task_dir / "tests" / "metadata.json").read_text())
    benchmark_id = meta["benchmark_id"]
    model_to_train = meta["model_to_train"]
    tasks_src = REPO_ROOT / "src" / "eval" / "tasks" / benchmark_id
    home = task_dir / "environment" / "home"
    repo = task_dir / "tests" / "repo"

    def same(staged: Path, source: Path, what: str) -> None:
        check(staged.exists(), f"{task_dir.name}: missing {what} ({staged})")
        if staged.exists():
            check(filecmp.cmp(staged, source, shallow=False),
                  f"{task_dir.name}: {what} differs from {source.relative_to(REPO_ROOT)}")

    def same_tree(staged: Path, source: Path, what: str,
                  skip_dir: str | None = None) -> None:
        check(staged.is_dir(), f"{task_dir.name}: missing dir {what}")
        if not staged.is_dir():
            return
        for src_file in sorted(source.rglob("*")):
            if not src_file.is_file():
                continue
            if skip_dir and skip_dir in src_file.relative_to(source).parts:
                continue
            same(staged / src_file.relative_to(source), src_file,
                 f"{what}/{src_file.relative_to(source)}")

    # --- B1. agent sandbox home == run_task.sh:55-155 -----------------------
    same(home / "task" / "evaluate.py", tasks_src / meta["eval_script"],
         "task/evaluate.py")
    same_tree(home / "task" / "templates", REPO_ROOT / "src" / "eval" / "templates",
              "task/templates")
    if (tasks_src / "evaluation_code").is_dir():
        same_tree(home / "task" / "evaluation_code", tasks_src / "evaluation_code",
                  "task/evaluation_code")
    if (tasks_src / "task_context").is_dir():
        for item in sorted((tasks_src / "task_context").iterdir()):
            if item.is_file():
                same(home / "task" / item.name, item, f"task/{item.name}")
    same_tree(home / ".codex", REPO_ROOT / "containers" / "other_home_data" / ".codex",
              ".codex")
    for name in ("check_cuda.py", "check_cuda_writing.py", "system_monitor.sh",
                 "timestamp_lines.py", "update_agent_cli.sh", "create_timer.sh"):
        same(home / name, REPO_ROOT / "src" / "utils" / name, name)
    same(home / "contamination_check.py",
         REPO_ROOT / "src" / "judges" / "judge_tools" / "contamination_check.py",
         "contamination_check.py")
    if (tasks_src / "test_data.json").exists():
        same(home / "test_data.json", tasks_src / "test_data.json", "test_data.json")

    # timer.sh must NOT be staged: preflight.sh generates it at container
    # start so CREATION_DATE is stamped near agent start, as upstream does.
    check(not (home / "task" / "timer.sh").exists(),
          f"{task_dir.name}: timer.sh was baked into the image; its CREATION_DATE "
          f"would be image build time, not agent start")

    # --- B2. verifier repo subtree ------------------------------------------
    same_tree(repo / "src" / "eval" / "tasks" / benchmark_id, tasks_src,
              f"repo/src/eval/tasks/{benchmark_id}")
    same_tree(repo / "src" / "eval" / "templates",
              REPO_ROOT / "src" / "eval" / "templates", "repo/src/eval/templates")
    same(repo / "src" / "judges" / "get_judge_prompt.py",
         REPO_ROOT / "src" / "judges" / "get_judge_prompt.py", "get_judge_prompt.py")
    same_tree(repo / "src" / "judges" / "judge_tools",
              REPO_ROOT / "src" / "judges" / "judge_tools", "judge_tools")
    for judge in cfg.ALL_JUDGES:
        for f in ("judge.conf", "prompt.md"):
            same(repo / "src" / "judges" / judge / f,
                 REPO_ROOT / "src" / "judges" / judge / f, f"{judge}/{f}")
    same(repo / "containers" / "delete_hf_models.py",
         REPO_ROOT / "containers" / "delete_hf_models.py", "delete_hf_models.py")
    # run_task.sh:324's parser package, at the upstream path so its flat
    # sibling imports resolve. __pycache__ is a build artefact of the
    # checkout, deliberately not staged.
    same_tree(repo / "src" / "trace_parsing",
              REPO_ROOT / "src" / "trace_parsing", "repo/src/trace_parsing",
              skip_dir="__pycache__")
    check(not (repo / "src" / "trace_parsing" / "__pycache__").exists(),
          f"{task_dir.name}: __pycache__ was staged into repo/src/trace_parsing")
    # sanitize_trace.py:33-34 hard-exits without a .env at the repo root.
    same(repo / ".env", REPO_ROOT / "example.env", "repo/.env")
    for d in (task_dir / "environment", task_dir / "tests"):
        same(d / "requirements-direct.txt",
             REPO_ROOT / "containers" / "requirements-direct.txt",
             f"{d.name}/requirements-direct.txt")

    # The relative path evaluate.py is invoked with, unchanged from
    # run_task.sh:421, has to resolve inside the staged tree.
    eval_cwd = repo / "src" / "eval" / "tasks" / benchmark_id
    resolved = (eval_cwd / "../../../../src/eval/templates").resolve()
    check(resolved == (repo / "src" / "eval" / "templates").resolve(),
          f"{task_dir.name}: --templates-dir ../../../../src/eval/templates "
          f"resolves to {resolved}, not the staged templates dir")

    # get_judge_prompt.py computes REPO_ROOT as its own parent.parent and
    # reads src/eval/tasks/<id>/info.json from there.
    check((repo / "src" / "eval" / "tasks" / benchmark_id / "info.json").exists(),
          f"{task_dir.name}: get_judge_prompt.py would not find info.json")

    # --- C. the prompt ------------------------------------------------------
    regenerated = build_tasks.generate_instruction(
        benchmark_id, model_to_train, str(meta["num_hours"]),
        build_tasks.PROMPT_AGENT, meta["num_gpus"],
    )
    actual = (task_dir / "instruction.md").read_text()
    check(actual == regenerated,
          f"{task_dir.name}: instruction.md differs from get_prompt.py output")

    # C2. The whole 1:1 claim, in one line, for every harness the task can be
    # run with: what the wrapper hands the real adapter must equal what
    # upstream's own pipeline produces for that agent name. Covers the split
    # between PROMPT_AGENT (what get_prompt.py saw) and metadata's real name.
    # Exhaustive over the wrappers that exist, derived from the module rather
    # than listed here so a new one cannot be added without being checked.
    # cursor_cli is absent because it has no wrapper (README divergence 15).
    wrapped = sorted(
        cls.PTB_AGENT_NAME
        for name, cls in vars(ptb_harness).items()
        if name.startswith("PtbHarness_")
    )
    check_eq(wrapped, ["claude", "codex", "gemini", "opencode"],
             "agents/ptb_harness.py wrapper roll-call")
    for upstream_agent in (meta["agent"], *wrapped):
        expected = build_tasks.generate_instruction(
            benchmark_id, model_to_train, str(meta["num_hours"]),
            upstream_agent, meta["num_gpus"],
        )
        check(ptb_harness.apply_agent_clause(actual, upstream_agent) == expected,
              f"{task_dir.name}: the wrapper's instruction for upstream agent "
              f"{upstream_agent!r} differs from get_prompt.py --agent "
              f"{upstream_agent}")

    # --- task.toml through harbor's own model -------------------------------
    from harbor.models.task.task import Task
    t = Task(task_dir)
    c = t.config
    check_eq(c.environment.workdir, cfg.SANDBOX_WORKDIR, f"{task_dir.name} workdir")
    check_eq(c.environment.cpus, cfg.REQUEST_CPUS, f"{task_dir.name} cpus")
    check_eq(c.environment.memory_mb, cfg.REQUEST_MEMORY_MB, f"{task_dir.name} memory_mb")
    check_eq(c.environment.storage_mb, cfg.REQUEST_DISK_MB, f"{task_dir.name} storage_mb")
    check_eq(c.environment.gpus, cfg.REQUEST_GPUS, f"{task_dir.name} gpus")
    check_eq(c.environment.gpu_types, cfg.GPU_TYPES, f"{task_dir.name} gpu_types")
    check(c.verifier.environment_mode.value == "separate",
          f"{task_dir.name}: verifier is not in separate mode")
    check(c.verifier.environment is not None and c.verifier.environment.gpus == 1,
          f"{task_dir.name}: verifier environment has no GPU (it runs vLLM)")
    sources = [a.source for a in c.artifacts]
    check(sources == [cfg.SANDBOX_HOME, cfg.AGENT_LOGS_DIR],
          f"{task_dir.name}: artifacts are {sources}, not the agent home plus "
          f"harbor's agent log dir (the raw trace test.sh turns into "
          f"solve_out.txt)")
    # An `exclude` on any artifact silently switches harbor from an uncapped
    # `docker compose cp` to a `tar czf` under a hardcoded 120 s timeout
    # (artifact_handler.py:335-347). final_model is ~8 GB of incompressible
    # weights and does not fit in 120 s, and the failure only shows up after
    # the agent's full budget is spent. Keep every artifact exclude-free.
    excluded = [(a.source, a.exclude) for a in c.artifacts if a.exclude]
    check(not excluded,
          f"{task_dir.name}: artifact exclude(s) {excluded} force harbor's "
          f"120s-capped tar path; the HF cache is linked in from "
          f"{cfg.HF_CACHE_MOUNT} instead so nothing needs excluding")
    # Every cache shard must sit outside the sandbox home for that to hold.
    # PTB_HF_CACHE_MOUNT is a colon-separated list: the cache ships as several
    # datasets to stay under the 1,000-file cap, and preflight.sh merges them.
    mounts = [m for m in c.environment.env.get("PTB_HF_CACHE_MOUNT", "").split(":") if m]
    check(bool(mounts), f"{task_dir.name}: PTB_HF_CACHE_MOUNT is unset")
    inside = [m for m in mounts if m.startswith(cfg.SANDBOX_HOME)]
    check(not inside,
          f"{task_dir.name}: cache shard(s) {inside} are inside "
          f"{cfg.SANDBOX_HOME}; the home artifact would copy the whole "
          f"HuggingFace cache")
    # tests/docker-compose.yaml is the only route a mount can take into a
    # separate verifier environment (trial/trial.py:681-692 vs :1299). Without
    # it the evaluation has no HF cache and gpqamain's gated dataset fails.
    # Every shard needs its own bind — a missing one is a silently partial
    # cache, which surfaces as a mystery download failure hours in.
    compose = (task_dir / "tests" / "docker-compose.yaml")
    body = compose.read_text() if compose.is_file() else ""
    unbound = [m for m in mounts if f"{m}:{m}:ro" not in body]
    check(not unbound,
          f"{task_dir.name}: tests/docker-compose.yaml does not bind {unbound} "
          f"into the verifier; the evaluation would run with a partial or "
          f"absent HF cache")
    check(c.environment.healthcheck is not None,
          f"{task_dir.name}: no healthcheck, so the CUDA gate and timer never run")

    # metadata's derived numbers
    check_eq(meta["zeroshot_baseline"],
             cfg.zeroshot_baseline(benchmark_id, model_to_train),
             f"{task_dir.name} zeroshot_baseline")
    check_eq(meta["benchmark_weight"], cfg.load_factors()[benchmark_id],
             f"{task_dir.name} benchmark_weight")

    # env the agent gets: only benchmarks that declare a key in info.json
    # should see it (run_task.sh's allowlist, benchmark half).
    required = build_tasks.read_required_api_keys(benchmark_id)
    for key in ("OPENAI_API_KEY", "OPENROUTER_API_KEY", "ANTHROPIC_API_KEY"):
        if key in required:
            check(key in c.environment.env,
                  f"{task_dir.name}: {key} is in info.json required_api_keys "
                  f"but not in [environment.env]")
        else:
            check(key not in c.environment.env,
                  f"{task_dir.name}: {key} is in [environment.env] but "
                  f"info.json does not require it — upstream withholds it")


# ---------------------------------------------------------------------------
# D. upstream line citations
# ---------------------------------------------------------------------------
#
# The port's comments carry ~180 `file:line` citations into upstream. They are
# the whole basis for reviewing it, and they rot silently: upstream inserts a
# line and every citation below it now points one line off. This caught real
# drift on 2026-09-01 — `judge_lib.sh:37` was cited for `ALL_JUDGES` after
# upstream moved it to :31, and six of score_run.py's `utils.py:` citations
# pointed into function bodies rather than at the `def` they named.
#
# Two checks: the line must exist, and where the citation is next to a name we
# can recognise, that name must appear at the cited line.

CITATION_RE = re.compile(r"\b(run_task\.sh|judge_lib\.sh|collect\.py|utils\.py):(\d+)")

CITED_SOURCES = {
    "run_task.sh": Path("src/run_task.sh"),
    "judge_lib.sh": Path("src/judges/judge_lib.sh"),
    "collect.py": Path("scripts/collect.py"),
    "utils.py": Path("scripts/utils.py"),
}

# (upstream file, line, token that must appear within +/-1 line of it).
# Only anchors worth pinning: the ones a reader navigates by.
CITATION_ANCHORS = [
    ("judge_lib.sh", 31, "ALL_JUDGES"),
    ("judge_lib.sh", 35, "JUDGE_DEFAULT_MODEL"),
    ("judge_lib.sh", 37, "JUDGE_CONTAINER"),
    ("judge_lib.sh", 167, "codex"),
    ("judge_lib.sh", 186, "parse_trace"),
    ("run_task.sh", 246, "--home"),
    ("run_task.sh", 419, "vllm_debug"),
    ("collect.py", 183, "baseline_data"),
    ("utils.py", 379, "def load_metrics"),
    ("utils.py", 410, "def judgement_path"),
    ("utils.py", 432, "def load_judgement"),
    ("utils.py", 468, "def optional_judgement_path"),
    ("utils.py", 517, "def load_api_judgement"),
    ("utils.py", 556, "def missing_required_judgements"),
    ("utils.py", 581, "def judgement_to_cell"),
    ("utils.py", 627, "def load_time_taken"),
]


def verify_citations() -> None:
    print("\nD. upstream line citations")
    src = {}
    for name, rel in CITED_SOURCES.items():
        path = REPO_ROOT / rel
        check(path.exists(), f"cited upstream file missing: {rel}")
        src[name] = path.read_text().split("\n") if path.exists() else []

    here = Path(__file__).resolve().parent
    scanned = [here / "template" / "tests" / "test.sh",
               here / "template" / "tests" / "score_run.py",
               here / "template" / "tests" / "Dockerfile",
               here / "template" / "environment" / "preflight.sh",
               here / "template" / "environment" / "Dockerfile",
               here / "DEVIATIONS.md"]

    n = 0
    for f in scanned:
        if not f.exists():
            continue
        for m in CITATION_RE.finditer(f.read_text()):
            name, line = m.group(1), int(m.group(2))
            n += 1
            check(1 <= line <= len(src[name]),
                  f"{f.name}: cites {name}:{line} but that file has "
                  f"{len(src[name])} lines")
    print(f"   {n} citations in range across {len(scanned)} files")

    for name, line, token in CITATION_ANCHORS:
        window = "\n".join(src[name][max(0, line - 2):line + 1])
        check(token.lower() in window.lower(),
              f"citation anchor drifted: {name}:{line} should be at/near "
              f"{token!r}, but that line reads "
              f"{src[name][line - 1].strip()[:70]!r}")
    print(f"   {len(CITATION_ANCHORS)} anchors still point at the right code")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--tasks", type=Path, required=True)
    # An APPROVED deviation is still a failure -- it must keep printing, keep
    # being counted, and keep appearing in the report. What --waive changes is
    # only whether it blocks the push.
    #
    # Without this the gate is all-or-nothing, so the single approved
    # deviation we ship with (D224, storage_mb 81920 vs 409600) makes it
    # impossible to ever push, and the only way out is to bypass the gate
    # entirely -- which would also bypass the 4820 checks that matter.
    #
    # Waiving is per-substring and deliberately narrow: a failure counts as
    # waived only if its text contains one of these. Any failure of any other
    # kind still exits non-zero.
    p.add_argument("--waive", action="append", default=[], metavar="SUBSTRING",
                   help="do not block the push on failures containing this "
                        "(they are still reported). Repeatable.")
    p.add_argument("--expect-waived", type=int, default=None, metavar="N",
                   help="require exactly N waived failures. Guards against a "
                        "waiver silently covering more than it was meant to.")
    args = p.parse_args()

    verify_constants()
    verify_agent_wrapper(args.tasks)
    verify_citations()

    task_dirs = sorted(d for d in args.tasks.iterdir() if (d / "task.toml").exists())
    print(f"\nB+C. {len(task_dirs)} generated task(s)")
    for d in task_dirs:
        before = len(failures)
        verify_task(d)
        status = "ok" if len(failures) == before else f"{len(failures) - before} FAILED"
        print(f"   {d.name:<48} {status}")

    waived = [f for f in failures
              if any(w in str(f) for w in args.waive)]
    blocking = [f for f in failures if f not in waived]

    print(f"\n{checks} checks, {len(failures)} failures "
          f"({len(waived)} waived, {len(blocking)} blocking)")
    for f in blocking:
        print(f"\n  FAIL: {f}")
    for f in waived:
        print(f"\n  WAIVED: {f}")

    if args.expect_waived is not None and len(waived) != args.expect_waived:
        print(f"\n  WAIVER MISMATCH: expected exactly {args.expect_waived} "
              f"waived failure(s), got {len(waived)}. The waiver is covering a "
              f"different set than it was written for -- refusing to pass.")
        return 1
    return 1 if blocking else 0


if __name__ == "__main__":
    sys.exit(main())
